### ISSUE TITLE
website teething issues

### ISSUE THREAD

**Issue by mk270** [barohcambridge/venue#10]
* company number absent
* phone number inconsistent ("Location, State, Country (000) 123 12345 email@yoursite.com") in banner of many pages, including contact page
* images in Gallery section have very different vibe from what's on Instagram/Facebook

**Comment by mcb30** [comment]
@mk270 Thanks for the heads-up: looks as though someone got carried away with trying out a new theme and didn't stop to check that it actually worked as expected.  I've fixed the most egregious errors, and will have words.

Image gallery does need to be updated, but that's part of a larger piece of work involving Google Maps images, etc, so I'm closing this for now.
