### ISSUE TITLE
electrical sockets around the upstairs balusters assort poorly with chairlegs

### ISSUE THREAD

**Issue by mk270** [barohcambridge/venue#2]
It's possible for patrons unwittingly to mash their chair legs against electrical plugs in some positions upstairs

**Comment by mcb30** [comment]
Checked and confirmed that this does affect several of the seats around the balcony.  There is no easy fix by using alternative sockets, so this is going to require getting new sockets fitted.  Tagging as such.

**Comment by mcb30** [comment]
@mk270 The electrician was in today, has devised a solution for the sockets, and will be getting back to us with a quote for the work.

**Comment by mcb30** [comment]
@mk270 This has now been fixed - come in and see for yourself :slightly_smiling_face:
