### ISSUE TITLE
unexpectedly attacked by aliens

### ISSUE THREAD

**Issue by mk270** [barohcambridge/venue#3]
The version of `Gyruss` on the arcade machine upstairs is not faithful to the 1983 version; in the first level, "2 warps to Neptune", the first four wave of alien spaceships fire upon the player. As you'll see from, e.g., https://www.youtube.com/watch?v=hF2m7EW9_lM&t=4s , in the first level the main enemy ships don't fire on the player, affording beginners the chance to get the bonus for eliminating a whole wave of ten.

**Comment by mcb30** [comment]
@mk270 Is this an issue with generally available emulations of the game?  If so, then we should probably push this as an upstream issue to the emulator project.  If not, then we should check the emulator and version present on the arcade machine.

**Comment by mcb30** [comment]
Closing for lack of response.
